config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :charges, only: [:new, :create]
  
  resources :wikis do 
    resources :collaborators, only: [:create, :destroy]
  end



  get 'downgrade' => 'charges#downgrade', :as => "downgrade"

  get 'about' => 'welcome#about'
  
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
    belongs_to :user
    belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :wikis, dependent: :destroy
  has_many :collaborators, dependent: :destroy
  has_many :collaborator_wikis, through: :collaborators, :source => :wiki
  
  
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  scope :all_except, -> (user, wiki){ where.not(id: user) }
  scope :exclude_collaborators, -> (wiki){where.not(id: wiki.users)}       
         
  after_initialize :init
  after_update :publicize
  
  
  def init
      self.role  ||= :standard  #will set the default value only if it's nil
  end
  
  def publicize
    if self.standard?
      self.wikis.update_all(private: false)
    end
  end

  enum role: [:standard, :admin, :premium]

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
  
  after_initialize :make_private
  
 
  private
  scope :free, -> { where( private: false) }
  
  after_initialize :make_private
  
  def make_private
      self.private  ||= false  #will set the default value only if it's nil
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  protect_from_forgery with: :exception
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    
    def create
        # Creates a Stripe Customer object, for associating
        # with the charge
        customer = Stripe::Customer.create(
        email: current_user.email,
        card: params[:stripeToken]
        )
 
         # Where the real magic happens
        charge = Stripe::Charge.create(
        customer: customer.id, # Note -- this is NOT the user_id in your app
        amount: 5000,
        description: "Premium Membership - #{current_user.email}",
        currency: 'usd'
        )
 
        current_user.update_attribute(:role, 'premium')
        
        if current_user.save!
            flash[:notice] = "Thanks for all the money, #{current_user.email}! You are now a Premium member!"
            redirect_to root_path 
        end
        # Stripe will send back CardErrors, with friendly messages
        # when something goes wrong.
        # This `rescue block` catches and displays those errors.
        rescue Stripe::CardError => e
        flash[:alert] = e.message
        redirect_to root_path
        
    end
    
    def new
        @stripe_btn_data = {
            key: "#{ Rails.configuration.stripe[:publishable_key] }",
            description: "Premium Membership - #{current_user.email}",
            amount: 5000
        }
        
    end
    
    def downgrade
        current_user.update_attribute(:role, 'standard')
        if current_user.save!
            flash[:notice] = "You've been downgraded :( "
            redirect_to root_path
        else 
            flash[:alert] = "Something went wrong, try again."
            redirect_to root_path
        end
    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
    
    def create
        @wiki = Wiki.find(params[:wiki_id])
        @user = User.where('email LIKE ?', "%#{params[:search]}%").all_except(current_user, @wiki).exclude_collaborators(@wiki).first
               
        if @user
            @collaborator = Collaborator.new(wiki: @wiki, user: @user)
            
            if @collaborator.save
                flash[:notice] = "User successfully added to wiki."
            else
                flash[:error] = "There was a problem adding user. Please try again."
            end
        else
            flash[:error] = "Sorry that wasn't a valid user email. Please try again."
        end
        redirect_to @wiki
    end
    
    def destroy
        @wiki = Wiki.find(params[:wiki_id])
        @collaborator = Collaborator.find(params[:id])
            
        if @collaborator.destroy
            flash[:notice] = "Member removed from wiki."
        else
            flash[:error] = "There was an error removing user."
        end
        redirect_to @wiki
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
     @wikis = policy_scope(Wiki)
  end

  def show
   @wiki = Wiki.friendly.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end
  
  def create
    @wiki = Wiki.new
    @wiki.assign_attributes(wiki_params)
    @wiki.user = current_user
    
    if @wiki.save
      flash[:notice] = "Wiki was saved!"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @collaborator = Collaborator.new
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)
 
    if @wiki.save
      flash[:notice] = "Wiki was updated!"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    end
  end
  
  private
  def wiki_params
    if current_user.admin? || current_user.premium? || @wiki.users.include?(current_user)
      params.require(:wiki).permit(:title, :body, :private, :users)
    else
      params.require(:wiki).permit(:title, :body)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        options = {
            filter_html:     true,
            hard_wrap:       true,
            link_attributes: { rel: 'nofollow', target: "_blank" },
            space_after_headers: true,
            fenced_code_blocks: true
        }

        extensions = {
            autolink:           true,
            superscript:        true,
            disable_indented_code_blocks: true
        }

        renderer = Redcarpet::Render::HTML.new(options)
        markdown = Redcarpet::Markdown.new(renderer, extensions)

        markdown.render(text).html_safe
    end
end

app/helpers/charges_helper.rb
module ChargesHelper

end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.haml
- if current_user.role != 'premium'
  = form_tag charges_path do
    %h2 Click Below and Pay to become a Premium Member! Only $50!
    %h4 Benefits include:
    %ul
      %li Satisfaction of being an elite premium member
      %li Street Cred
      %li Ability to create Private Wikis
    %script.stripe-button{"data-amount" => "#{@stripe_btn_data[:amount]}", "data-description" => "#{@stripe_btn_data[:description]}", "data-key" => "#{@stripe_btn_data[:key]}", :src => "https://checkout.stripe.com/checkout.js"}
- else
  %h4 You don't have to do this! But there are no refunds... so whatever. Fair warning though: all of your private wikis will become public. You still sure?
  = button_to "Downgrade", {action: "downgrade"}, method: :get

app/views/collaborators/_collaborators.htm.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h4>Collaborators</h4>
  </div>
  <div class="panel-body">
    <% wiki.collaborators.each do |collaborator| %>
      <h4><span class="glyphicon glyphicon-user" aria-hidden="true"> <%= collaborator.user.email %> <%= link_to "Remove", [wiki, collaborator], method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Are you sure you want to remove this user?'} if current_user.is_owner_of?(wiki)%></span></h4>
    <% end %>
    <% if current_user.is_owner_of? wiki %>
      <%= render partial: 'collaborators/form', locals: { wiki: wiki, collaborator: collaborator} %>
    <% end %>
  </div>
</div>

app/views/collaborators/_form.html.haml
.panel.panel-info
  .panel-heading
    %h4 Collaborators
  .panel-body
    - wiki.collaborators.each do |collaborator|
      %h4
        %span.glyphicon.glyphicon-user{"aria-hidden" => "true"}
          = collaborator.user.email
          = link_to "Remove", [wiki, collaborator], method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Are you sure you want to remove this user?'} if current_user == wiki.user
    - if current_user == wiki.user
      = form_tag [wiki, collaborator] do
        = text_field_tag :search, params[:search]
        = submit_tag "Add User"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blocipedia
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      %ul.nav.nav-tabs
        %li= link_to "Home", root_path
        %li= link_to "About", about_path
        %li= link_to "Wikis", wikis_path
        - if user_signed_in? && current_user.role != 'premium'
          %li= link_to "Upgrade", new_charge_path
        - if user_signed_in? && current_user.role == 'premium'
          %li= link_to "Downgrade", new_charge_path
      .pull-right
        - if user_signed_in?
          Signed in as:
          %strong= current_user.email
          %br/
          Member Status:
          %strong= current_user.role
          %br/
          = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
          \- #{link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
        - else
          = link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'
          \-
          \#{link_to "Sign In", new_user_session_path, :class => 'navbar-link'}
      - if flash[:notice]
        .alert.alert-success
          %button.close{"data-dismiss" => "alert", :type => "button"} ×
          = flash[:notice]
      - elsif flash[:alert]
        .alert.alert-warning
          %button.close{"data-dismiss" => "alert", :type => "button"} ×
          = flash[:alert]
      = yield

app/views/welcome/about.html.haml
%h1 Welcome#about
%p Find me in app/views/welcome/about.html.erb

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.erb

app/views/wikis/_form.html.haml
.col-md-8
  = form_for @wiki do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control', placeholder: "Enter wiki title"
    .form-group
      = f.label :body
      = f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body"
    - if current_user.admin? || current_user.premium?
      .form-group
        = f.label :private, class: 'checkbox' do
          = f.check_box :private
          Private wiki
    .form-group
      = f.submit "Save", class: 'btn btn-success'

app/views/wikis/edit.html.haml
%h1 Edit Wiki
.row
  .col-md-4
    %p Guidelines for wikis
    %ul
      %li Make it SFW
      %li Focus on facts
      %li Keep the dream alive
  = render partial: 'form', locals: { wiki: @wiki } 
  .row
    - if @wiki.private?
      = render partial: 'collaborators/form', locals: { wiki: @wiki, collaborator: @collaborator }

  

app/views/wikis/index.html.haml
%h1 All Wikis
.col-md-4
  = link_to "New Wiki", new_wiki_path, class: 'btn btn-success'
%br/
%br/
- @wikis.each do |wiki|
  .media
    .media-body
      %h4.media-heading
        = link_to wiki.title, wiki

app/views/wikis/new.html.haml
%h1 New Wiki
.row
  .col-md-4
    %p Guidelines for wikis
    %ul
      %li Make it SFW
      %li Focus on facts
      %li Keep the dream alive 
  = render partial: 'form', locals: { wiki: @wiki }
  

app/views/wikis/show.html.haml
%h1= markdown(@wiki.title)
.row
  .col-md-8
    %p= markdown(@wiki.body)
  .col-md-4
    = link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success'
    - if policy(@wiki).destroy?
      = link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'}